### PR TITLE
Update to 1.1.11 and re-render

### PR DESCRIPTION
**Pull request by mcs07**

### CODE REVIEW

**Comment by mcs07** [comment]
Closes #3

**Comment by synapticarbors** [comment]
@mcs07 - Would you mind updating this to 1.1.11? Also do you know how to re-render the feedstock. If not, see: 

http://conda-forge.github.io/docs/conda_smithy.html

If you don't have time, I can open a new PR. 

@ocefpaf - Could you please review this once @mcs07 has updated the PR?

**Comment by ocefpaf** [comment]
> @ocefpaf - Could you please review this once @mcs07 has updated the PR?

Sure. Unless you want to get this merged first so both versions are available, but I am guessing `1.1.11` is a bugfix release.

**Comment by ocefpaf** [comment]
@mcs07 Do you want to add yourself as a maintainer here? That way you can self-merge updates like this one in the future.

**Pull request merged**
