### PR TITLE
Fix runtime dependencies

### PR DESCRIPTION
**Pull request by fcollonval**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

greenlet is missing from runtime dependencies

I added pip check in test to capture changes in runtime dependencies in the future.

### CODE REVIEW

**Comment by fcollonval** [comment]
@conda-forge-admin, please rerender

**Comment by fcollonval** [comment]
greenlet 0.4.16 (the latest compatible version for sqlalchemy) is not the latest release. So unfortunately the pypy 37 and py39 version of greenlet 0.4.16 is not available. This can be fixed upstream.

**Comment by nehaljwani** [comment]
Waiting on https://github.com/conda-forge/greenlet-feedstock/pull/15 before restarting CI.

**Comment by jan-janssen** [comment]
@nehaljwani the tests passed - can you merge this?

**Pull request merged**
